-- MySQL Script generated by MySQL Workbench
-- Wed Apr 11 19:02:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testcreatedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testcreatedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testcreatedb` DEFAULT CHARACTER SET utf8 ;
USE `logindb` ;

USE `testcreatedb` ;

-- -----------------------------------------------------
-- Table `testcreatedb`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testcreatedb`.`registration` (
  `id` INT(11) NOT NULL,
  `first` VARCHAR(255) NULL DEFAULT NULL,
  `last` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE DEFINER=`root`@`localhost` 
PROCEDURE `insertProcedure`(IN in_id int,IN in_first varchar(45),IN in_last varchar(45),IN in_age int)
BEGIN
 INSERT INTO registration (id,first,last,age) values (in_id ,in_first,in_last,in_age);
END

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
