-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 10:46:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jsondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jsondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jsondb` DEFAULT CHARACTER SET utf8 ;
USE `jsondb` ;

-- -----------------------------------------------------
-- Table `jsondb`.`jsontb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsondb`.`jsontb` (
  `id` INT(11) NOT NULL,
  `friend_list` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
